# Generated by Django 5.0.6 on 2024-06-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birthdays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('department', models.CharField(blank=True, max_length=150, verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Именинник',
                'verbose_name_plural': 'Именинники',
                'ordering': ('-birthday',),
            },
        ),
    ]
